AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sorteios-backend-serverless

  Sample SAM Template for sorteios-backend-serverless

Globals:
  Function:
    Timeout: 100
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        EVENT_BUS_NAME: SorteiosEventBus
        EVENT_PATTERN_SOURCE: totalpag-digital-account
  Api:
    TracingEnabled: true

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - sbox
      - prd
    Description: Environment in which the application will be deployed. Allowed values [dev, sbox, prd]
    Default: dev
Resources:
  ##########################################################################
  #                                 SQS                                    #
  ##########################################################################
  EventBridgeToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: SQS:SendMessage
            Resource: "*"
      Queues:
        - !Ref CreateOrderQueue
        - !Ref NotifyOrderPaymentQueue

  CreateOrderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CreateOrder
      VisibilityTimeout: 110
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CreateOrderDLQ.Arn
        maxReceiveCount: 3
  CreateOrderDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CreateOrderDLQ
      VisibilityTimeout: 110

  NotifyOrderPaymentQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotifyOrderPayment
      VisibilityTimeout: 110
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt NotifyOrderPaymentDLQ.Arn
        maxReceiveCount: 3
  NotifyOrderPaymentDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotifyOrderPaymentDLQ
      VisibilityTimeout: 110
  ##########################################################################
  #                              Layers                                   #
  ##########################################################################
  PrizeDrawDepsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PrizeDrawDepsLayer
      Description: Dependencies layer for the prize draw lambda
      ContentUri: backend/layers/deps
      CompatibleRuntimes:
        - nodejs20.x
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs20.x
      BuildArchitecture: x86_64
  ##########################################################################
  #                                 Lambdas                                #
  ##########################################################################
  # CreateOrderFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: CreateOrder
  #     CodeUri: backend/
  #     Handler: create-prize-draw.CreateOrderHandler
  #     Runtime: nodejs20.x
  #     Architectures:
  #       - x86_64
  #     Layers:
  #       - !Ref PrizeDrawDepsLayer
  #     Policies:
  #       - AWSLambdaBasicExecutionRole
  #       - Statement:
  #           - Effect: Allow
  #             Action:
  #               - events:PutEvents
  #             Resource: "*"
  #           - Effect: Allow
  #             Action:
  #               - dynamodb:PutItem
  #               - dynamodb:GetItem
  #               - dynamodb:UpdateItem
  #               - dynamodb:DeleteItem
  #               - dynamodb:Scan
  #               - dynamodb:Query
  #               - dynamodb:BatchWriteItem
  #             Resource: "*"
  #     Events:
  #       CreateOrderEvent:
  #         Type: SQS
  #         Properties:
  #           Queue: !GetAtt CreateOrderQueue.Arn
  #           BatchSize: 10
  #           FunctionResponseTypes:
  #             - ReportBatchItemFailures
  #   Metadata:
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: es2020
  #       Sourcemap: true
  #       EntryPoints:
  #         - src/lambdas/create-prize-draw.ts
  #       External:
  #         - "@aws-sdk/client-eventbridge"
  #         - "@aws-sdk/client-dynamodb"
  #         - zod
  #         - zod-validation-error

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateOrder
      CodeUri: backend/
      Handler: create-order.createOrderHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Layers:
        - !Ref PrizeDrawDepsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        CreateOrderEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CreateOrderQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/lambdas/create-order.ts
        External:
          - "@aws-sdk/client-eventbridge"
          - "@aws-sdk/client-dynamodb"
          - zod
          - zod-validation-error
          - knex
          - axios
          - qrcode

  NotifyOrderPaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotifyOrderPayment
      CodeUri: backend/
      Handler: notify-payment.notifyPaymentHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        NotifyOrderPaymentEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NotifyOrderPaymentQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/lambdas/notify-payment.ts
        External:
          - "@aws-sdk/client-eventbridge"
          - "@aws-sdk/client-dynamodb"
          - zod
          - zod-validation-error
          - knex
          - axios
          - qrcode
# sam build; sam local invoke CreateOrder --event events/event.json
